tasks:
    path: /
    controller: App\Controller\TaskController::index
my_tasks:
    path: /mis-tareas
    controller: App\Controller\TaskController::myTasks

register:
    path: /registro
    controller: App\Controller\UserController::register
login:
    path: /login
    controller: App\Controller\UserController::login

logout:
    path: /logout

task_detail:
    path: /tarea/{id}
    controller: App\Controller\TaskController::detail

task_creation:
    path: /crear/tarea
    controller: App\Controller\TaskController::creation

task_edit:
    path: /editar-tarea/{id}
    controller: App\Controller\TaskController::edit

task_delete:
    path: /eliminar-tarea/{id}
    controller: App\Controller\TaskController::delete